#!/usr/bin/env python3
"""Exercise real Makefile generation with equal archive mtimes and failed xxd."""
import os
from pathlib import Path
import subprocess
import tempfile

repo = Path(__file__).resolve().parents[1]
makefile = repo / 'core/legacy/source/Makefile'
with tempfile.TemporaryDirectory(prefix='star-default-generation-') as tmp:
    root = Path(tmp)
    source = root / 'parametersDefault'
    header = root / 'parametersDefault.xxd'
    source.write_text('soloFlexCellCaller tag-aware\nsoloFlexFilteredGeneList -\n')
    header.write_text('stale generated default bytes\n')
    archive_time = 1_700_000_000_000_000_000
    os.utime(source, ns=(archive_time, archive_time))
    os.utime(header, ns=(archive_time, archive_time))
    # Suppress unrelated dependency scanning; use the real generation rule.
    (root / 'Depend.list').write_text('')
    command = ['make', '-f', str(makefile), '-o', 'Depend.list',
               'WITH_CHROMAP=0', 'parametersDefault.xxd']
    expected = subprocess.check_output(['xxd', '-i', source.name], cwd=root)
    subprocess.run(command, cwd=root, check=True, stdout=subprocess.PIPE)
    assert header.read_bytes() == expected, 'equal-mtime stale header survived'
    before = header.stat().st_mtime_ns
    # A cached build must leave correct generated bytes and mtime untouched.
    subprocess.run(command, cwd=root, check=True, stdout=subprocess.PIPE)
    assert header.stat().st_mtime_ns == before, 'unchanged header was rewritten'
    source.write_text(source.read_text() + 'extraParameter changed\n')
    os.utime(source, ns=(archive_time, archive_time))
    subprocess.run(command, cwd=root, check=True, stdout=subprocess.PIPE)
    assert header.read_bytes() == subprocess.check_output(
        ['xxd', '-i', source.name], cwd=root), 'older-mtime source was ignored'
    good = header.read_bytes()
    fakebin = root / 'bin'
    fakebin.mkdir()
    fake = fakebin / 'xxd'
    fake.write_text('#!/bin/sh\nprintf "partial failed output\\n"\nexit 7\n')
    fake.chmod(0o755)
    failed = subprocess.run(command, cwd=root, env=dict(os.environ,
                            PATH=str(fakebin) + ':' + os.environ['PATH']),
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    assert failed.returncode != 0, 'failed generator was accepted'
    assert header.read_bytes() == good, 'failed generator replaced good header'
    assert not list(root.glob('parametersDefault.xxd.*')), 'temporary file leaked'
print('PASS: equal-mtime regeneration, cached mtime, older input, atomic failure')
