#ifndef STAR_FLEX_SAMPLE_TAG_CACHE_H
#define STAR_FLEX_SAMPLE_TAG_CACHE_H

#include <array>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <vector>

namespace star {
namespace flex {

// Perfect-hash cache for an eight-base sample tag. The packed two-bit tag is
// the table index, so H0 and H1 are separate constant-time lookups. H0 is
// populated first and always has precedence. H1 entries are generated from
// the supplied table; variants generated by multiple owners are marked
// ambiguous at construction and can never be assigned at runtime.
class SampleTagCache {
public:
    enum class Tier : std::uint8_t { Miss = 0, H0 = 1, H1 = 2 };

    struct Result {
        Result() : owner(0), tier(Tier::Miss), ambiguous(false) {}
        Result(std::uint16_t ownerIn, Tier tierIn, bool ambiguousIn)
            : owner(ownerIn), tier(tierIn), ambiguous(ambiguousIn) {}

        std::uint16_t owner;
        Tier tier;
        bool ambiguous;
    };

    struct Stats {
        std::uint32_t exact = 0;
        std::uint32_t mismatch1 = 0;
        std::uint32_t ambiguous = 0;
    };

    void build(const std::vector<std::uint16_t>& codes,
               const std::vector<std::uint16_t>& owners)
    {
        if (codes.size() != owners.size()) {
            throw std::invalid_argument("sample-tag code/owner size mismatch");
        }

        h0_.fill(kEmpty);
        h1_.fill(kEmpty);
        stats_ = Stats{};

        for (std::size_t i = 0; i < codes.size(); ++i) {
            const std::uint16_t owner = owners[i];
            if (owner == kEmpty || owner == kAmbiguous) {
                throw std::invalid_argument("sample-tag owner is reserved");
            }
            setOwner(h0_[codes[i]], owner);
        }

        for (std::size_t i = 0; i < codes.size(); ++i) {
            const std::uint16_t code = codes[i];
            const std::uint16_t owner = owners[i];
            for (unsigned position = 0; position < 8u; ++position) {
                const unsigned shift = 2u * position;
                const std::uint16_t have = static_cast<std::uint16_t>((code >> shift) & 0x3u);
                for (std::uint16_t base = 0; base < 4u; ++base) {
                    if (base == have) continue;
                    const std::uint16_t neighbour = static_cast<std::uint16_t>(
                        (code & ~(0x3u << shift)) | (base << shift));
                    if (h0_[neighbour] == kEmpty) {
                        setOwner(h1_[neighbour], owner);
                    }
                }
            }
        }

        for (std::size_t index = 0; index < kTableSize; ++index) {
            if (h0_[index] == kAmbiguous) ++stats_.ambiguous;
            else if (h0_[index] != kEmpty) ++stats_.exact;

            if (h1_[index] == kAmbiguous) ++stats_.ambiguous;
            else if (h1_[index] != kEmpty) ++stats_.mismatch1;
        }
    }

    Result lookup(std::uint16_t code, bool allowMismatch) const
    {
        const std::uint16_t exact = h0_[code];
        if (exact == kAmbiguous) return Result{0u, Tier::H0, true};
        if (exact != kEmpty) return Result{exact, Tier::H0, false};
        if (!allowMismatch) return Result{};

        const std::uint16_t mismatch = h1_[code];
        if (mismatch == kAmbiguous) return Result{0u, Tier::H1, true};
        if (mismatch != kEmpty) return Result{mismatch, Tier::H1, false};
        return Result{};
    }

    const Stats& stats() const { return stats_; }

private:
    static constexpr std::size_t kTableSize = 1u << 16u;
    static constexpr std::uint16_t kEmpty = 0u;
    static constexpr std::uint16_t kAmbiguous = 0xFFFFu;

    static void setOwner(std::uint16_t& slot, std::uint16_t owner)
    {
        if (slot == kEmpty) slot = owner;
        else if (slot != owner) slot = kAmbiguous;
    }

    std::array<std::uint16_t, kTableSize> h0_{};
    std::array<std::uint16_t, kTableSize> h1_{};
    Stats stats_{};
};

} // namespace flex
} // namespace star

#endif
